### ISSUE TITLE
add birthdate propery to APP ENUM

### ISSUE THREAD

**Issue by outbreaker** [outbreaker/Demis-Adapter-Configuration-UI#16]

**Comment by outbreaker** [comment]
@IlenaPuls ist das Feld ein Experten Feld oder eher ein normales?

**Comment by IlenaPuls** [comment]
Experten Feld. Default Value/Vorkonfiguriert ist: yyyyMMdd

**Comment by outbreaker** [comment]
> Experten Feld. Default Value/Vorkonfiguriert ist: yyyyMMdd

ok so ist es umgesetzt, pull request kommt nach den anderen
