### ISSUE TITLE
demis-adapter-api.properties and labor1.json are missing

### ISSUE THREAD

**Issue by dlang0815** [outbreaker/Demis-Adapter-Configuration-UI#30]
Hi,
i choose the main directory in the app, but the demis-adapter-api.properties and labor1.json are missing. 

What am i doing wrong?

regards
dlang0815

![image](https://user-images.githubusercontent.com/77096410/103869072-1ae89c80-50ca-11eb-83fa-e131fe8ff52f.png)

**Comment by outbreaker** [comment]
Hi @dlang0815 ,

this is a Bug an would be fixed soon. 
Your configuration contains proxy port definition without value, or? Please remove the line and try again. 
This empty string also leads to an error in the adapter. If the parameter is not needed then  remove it from configuration. 

BR

**Comment by outbreaker** [comment]
Hi @dlang0815,

the bug is fixed and available in Release 1.1.1: https://github.com/outbreaker/Demis-Adapter-Configuration-UI/releases/tag/1.1.1

BR

**Comment by dlang0815** [comment]
Hi @outbreaker ,

thanks for the quick response!
